# Generated by Django 2.2.13 on 2020-06-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_name', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('background_description', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('background_type', models.IntegerField(choices=[(1, 'Photo'), (2, 'Music')])),
            ],
        ),
    ]
