# Generated by Django 2.2.13 on 2020-06-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='admin status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='guest status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_investor',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='investor status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_startup',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='startup status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='user status'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
