# Generated by Django 2.2.13 on 2020-06-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200607_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.IntegerField(choices=[(1, 'Аватар 1'), (2, 'Аватар 2'), (3, 'Аватар 3')], default=1),
        ),
    ]
