# Generated by Django 2.2.13 on 2020-06-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200607_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test1591508842.3026085@test.de', max_length=150, unique=True, verbose_name='Email'),
        ),
    ]
