# Generated by Django 2.2.13 on 2020-06-07 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20200607_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.Video'),
        ),
    ]
