# Generated by Django 2.2.13 on 2020-06-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_remove_tag_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
