# Generated by Django 2.2.13 on 2020-06-07 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networking',
            name='user_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networking_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
